### ISSUE TITLE
DiscordJs v13

### ISSUE THREAD

**Issue by TKDBB84** [robbot-discord/winston-discordjs#309]
Do you have any interest in upgrading this library to support DiscordJS v13?  I've started the process over on my fork of this project.

**Comment by robertsmieja** [comment]
Sure, if you've already started the work I'd be happy to accept a PR.

Otherwise I'm happy to upgrade it. I didn't realize Discord.js v13 was out already.

**Comment by TKDBB84** [comment]
I can adjust my branch and create a PR, should be minimal work, i'll try to get to it sometime this week.

**Comment by robertsmieja** [comment]
Resolved per PR - https://github.com/robbot-discord/winston-discordjs/pull/315
Published new major version since this is a breaking change - https://www.npmjs.com/package/winston-discordjs/v/3.0.0
